name: tutorials
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - numpy>=1.14.3
  - pandas>=1.0.0
  - scikit-learn>=0.19.1
  - matplotlib>=3.0.2
  - cloudpickle>=0.6.1
  - pip
  - pip:
    - mlflow
